# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7871385cb53d915fb3029606aa29c42a04b705d6e75b6d036b23f2b2bf94cb5b49b419a011043caff60b26badf81b6d3ff5610650621a1e1c90376b08049880a

test:
  secret_key_base: 5441ac8dd5ca4341b4397c3010005b274e5679d33440995b104f62cf8a4a34bb7f36e6be021e5892a41f123e05a969104d6822e6c872b89e16133501eaa6dd2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
